### ISSUE TITLE
钱包SDK的源代码什么时候放出？

### ISSUE THREAD

**Issue by erzaxs** [lomocoin/wallet-sdk-demo#1]
目前工程里只有aar，什么时候放出SDK源代码？

**Comment by erzaxs** [comment]
代码是开发完成的了，内部可能需要在评估下接口设计后才放出，很快了。
大家可以订阅这个issure!

目前支持的特性：
私钥生成、bip44、构造交易、签名交易、多重签名
币种：BTC,USDT,ETH,ERC20

**Comment by erzaxs** [comment]
Hallo 大家好， 我们的SDK源代码已经转为public 了，欢迎大家试用，在这里

https://github.com/dabankio/wallet-core

另外，留意下最新的代码不在master分支（我们会尽快合并），参考issues.

**Comment by VVanaheim** [comment]
可以去看看优盾官网的开源代码，互相交流学习一下

**Comment by Aimeelu668** [comment]
楼上说的是https://www.uduncloud.com   吗？pretty good
