### ISSUE TITLE
大佬，你这是用的那个开发工具啊，vscode还是Intellij IDEA啊？我只用过Android Studio.

### ISSUE THREAD

**Issue by dewi23** [lomocoin/wallet-sdk-demo#3]

**Comment by erzaxs** [comment]
不要叫我大佬😂，我只是个普通的程序员。。

以前做java的时候用Intellij IDEA，后来不怎么用就没买了（主要是有段时间太穷了╮(╯▽╰)╭）。

我现在一般主要用vscode，比较轻量，好定制，免费用的心安理得，插件也比较丰富。基本上js ts golang flutter 都ok。

安卓必要的时候还是用Android Studio,如果要写java就用Intellij IDEA 社区版。

工具吧，自己用着顺手就行。

**Comment by dewi23** [comment]
我主要是用Android Studio.Intellij IDEA我自己用的破解版本。



------------------ 原始邮件 ------------------
发件人: "孙显松"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 中午11:01
收件人: "lomocoin/wallet-sdk-demo"<wallet-sdk-demo@noreply.github.com>; 
抄送: "!`夜色下美景"<395374865@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lomocoin/wallet-sdk-demo] 大佬，你这是用的那个开发工具啊，vscode还是Intellij IDEA啊？我只用过Android Studio. (#3)




不要叫我大佬😂，我只是个普通的程序员。。
 
以前做java的时候用Intellij IDEA，后来不怎么用就没买了（主要是有段时间太穷了╮(╯▽╰)╭）。
 
我现在一般主要用vscode，比较轻量，好定制，免费用的心安理得，插件也比较丰富。基本上js ts golang flutter 都ok。
 
安卓必要的时候还是用Android Studio,如果要写java就用Intellij IDEA 社区版。
 
工具吧，自己用着顺手就行。
